title: Shuangfei Wei's Homepage
page-top-title: Wei Shuangfei
top-section-bg-text: Computer Science
home-subtitle: Shuangfei Wei&ensp;|&ensp;魏双飞
copyright-text: '&copy; Shuangfei Wei 2023-2026. All Rights Reserved.'
